### ISSUE TITLE
Can we assume materials will never be null/malformed? 

### ISSUE THREAD

**Issue by WChrisK** [dilevin/computer-graphics-ray-tracing#1]
Some of the .json files in the data folder will segfault because there's no materials in the code I've done for this assignment.

Are we expected to handle this? (if so, what do you want us to do?)

**Comment by dilevin** [comment]
You don't have to run your code on the .json files that do not define materials.

**Comment by WyattLiu** [comment]
Is this the reason we have segfaults for two spheres on a plane and inside the sphere?

**Comment by dilevin** [comment]
Yes (see issue [#4](https://github.com/dilevin/computer-graphics-ray-tracing/issues/4))
