### ISSUE TITLE
Reasonable run time for bunny.json

### ISSUE THREAD

**Issue by ACalza** [dilevin/computer-graphics-ray-tracing#10]
Someone posted about this on blackboard, but I think it's better suited here. 

What is a reasonable runtime for bunny.json? Right now in order to cut the time from 30 minutes, I paralalized the code and runs significantly faster (and yes I'm using release build as well). It takes about 15 minutes on my dual core MacBook with the threading. I believe that's reasonable considering that the triangle-soup algorithm is fairly naive. Wondering if people are getting rough run times, and what's acceptable.

**Comment by WyattLiu** [comment]
Dual core macbook pro sounds about right, I am on 6700K in 52s, 5 reflections. Also note that you will have more cache misses which takes hundreds of cycles to fetch. Probably perf will tell you that. Also in order to parallel well, you will have to deal with affinity or just use openmp.
