### ISSUE TITLE
Code relocation error for libhw2 (with potential fix)

### ISSUE THREAD

**Issue by alextechcc** [dilevin/computer-graphics-ray-tracing#12]
When using the provided library for hw2:

```
/usr/bin/ld: ../lib/debug/linux/libhw2.a(Plane.cpp.o): relocation R_X86_64_32 against `.bss' ca
n not be used when making a PIE object; recompile with -fPIC
```
(same for all used sources in library)

I believe that the library needs to be compiled with this added to CMakeLists.txt
`set(CMAKE_POSITION_INDEPENDENT_CODE ON)`

**Comment by rin-23** [comment]
Are you using ubuntu18?

**Comment by alextechcc** [comment]
Nope. Arch Linux, GCC 8.2.1, which might be stricter about code relocation.
