### ISSUE TITLE
whats wrong with my bunny

### ISSUE THREAD

**Issue by Kubik42** [dilevin/computer-graphics-ray-tracing#13]
Is there something wrong with my implementation? The other examples (sphere-and-plane, sphere-packing) look exactly as the given images, yet my bunny is like this:

![bunny](https://user-images.githubusercontent.com/11563877/52023802-8da77100-24cc-11e9-8040-edef6a3b52e8.png)

I'm using the provided precompiled a2 code btw

**Comment by ACalza** [comment]
Something something max_t. You're welcome.

**Comment by Kubik42** [comment]
completely overlooked that bit, thanks!
