### ISSUE TITLE
Sample output images

### ISSUE THREAD

**Issue by desmondlzy** [dilevin/computer-graphics-ray-tracing#16]
Hi, I just wonder if we can have the sample output images for all the given json files as we have in assignment 2. 

Thanks a lot!

**Comment by darren-moore** [comment]
Thanks for asking- I'll add `.ppm` sample outputs this weekend. Stay tuned!

**Comment by darren-moore** [comment]
Will add as soon as I figure what settings we'll run your submitted code with. In the mean time, running ImageMagick `compare` against the `.png` files in the README will help you identify most issues.

**Comment by darren-moore** [comment]
Done. See https://github.com/dilevin/computer-graphics-ray-tracing/issues/23

**Comment by desmondlzy** [comment]
gotcha, thanks!
