### ISSUE TITLE
max_depth

### ISSUE THREAD

**Issue by charlesvong** [dilevin/computer-graphics-ray-tracing#21]
I noticed that max_depth wasn't defined anywhere within the codebase or the input json files, so I was wondering what max_depth was used to produce the solution images.

**Comment by darren-moore** [comment]
Good question. I'll post this along with the promised reference solutions: https://github.com/dilevin/computer-graphics-ray-tracing/issues/16

**Comment by darren-moore** [comment]
Done. See https://github.com/dilevin/computer-graphics-ray-tracing/issues/23.
