### ISSUE TITLE
How small should min_t be for the shadows?

### ISSUE THREAD

**Issue by Cheryl-Lao** [dilevin/computer-graphics-ray-tracing#22]
We talked about how min_t should be some small number in class, but what was used for the reference images?

**Comment by darren-moore** [comment]
Good question. I'll post this along with the promised reference solutions: https://github.com/dilevin/computer-graphics-ray-tracing/issues/16

**Comment by Cheryl-Lao** [comment]
Awesome, thank you!

**Comment by darren-moore** [comment]
Done. See https://github.com/dilevin/computer-graphics-ray-tracing/issues/23
