### ISSUE TITLE
Weird Specular Lights

### ISSUE THREAD

**Issue by BlackSpade741** [dilevin/computer-graphics-ray-tracing#25]
This is what my sphere and plane looks like right now: 

![image](https://user-images.githubusercontent.com/24865967/73221159-331c1180-412e-11ea-8c7a-a8299d0e8fbc.png)

Everything seems to be in the right place, besides the one highlight spot on the left side of the sphere that is in the wrong place. I was thinking that this could be a problem with the direction of one of the lights, but it doesn't seem to make sense if all the shadows & lighting is correct. Would love to pick someone's brain about this issue.

**Comment by pauldpong** [comment]
I had a similar problem. My fix was that the ray.direction is not normalized (also needs to be in negative). Both the "v" and "l" have to be normalized before we do the half vector calc

**Comment by BlackSpade741** [comment]
Weird, when I do make it negative the specular lights don't appear at all, and I'm already normalizing the vectors, guess it's something different *shrug*

**Comment by pauldpong** [comment]
It looks like the vector is calculated on the wrong side of the normal

**Comment by BlackSpade741** [comment]
Solved! Mistakenly used the ray for shadow calculation instead lol, silly mistake.
