### ISSUE TITLE
Expected bunny raytracing runtime?

### ISSUE THREAD

**Issue by mshoe** [dilevin/computer-graphics-ray-tracing#27]
How long should we expect raytracing to take for the bunny?

**Comment by darren-moore** [comment]
* With the settings here (https://github.com/dilevin/computer-graphics-ray-tracing/issues/23), ~6:30 minutes on my i7-6600U laptop processor. I can report back with a test on the CDF machines later.
* Consider using the included hw2 lib. Its `Triangle::intersection` code is pretty speedy compared to some possible implementations.
* We're not grading you on efficiency.
* Relevant issue: https://github.com/dilevin/computer-graphics-ray-tracing/issues/10
* (for interest) investigate OpenMP and try using `#pragma omp parallel for` with the `main.cpp` for loop. Runtime was cut to ~2:45 on my laptop.
    * Convince yourself that ray tracing is [embarrassingly parallel](https://en.wikipedia.org/wiki/Embarrassingly_parallel) first.

**Comment by radiolariax** [comment]
Where do we add -fopenmp to the Makefile to enable OpenMP parallelization?

**Comment by darren-moore** [comment]
> Where do we add -fopenmp to the Makefile to enable OpenMP parallelization?

You can add the compiler option using  `-DCMAKE_CXX_FLAGS="-fopenmp"`
e.g. `cmake -DCMAKE_CXX_FLAGS="-fopenmp" -DCMAKE_BUILD_TYPE=Release -DHW2LIB_DIR=../lib/release/linux/ ..`

**Comment by darren-moore** [comment]
> I can report back with a test on the CDF machines later.

for `bunny` I'm getting ~4:15 on CDF, and if I multithread(for fun), ~1:15.
