### ISSUE TITLE
Is the l and v vectors unit vectors?

### ISSUE THREAD

**Issue by RaihanFaruque** [dilevin/computer-graphics-ray-tracing#29]

**Comment by darren-moore** [comment]
I'm guessing your talking about the `l` and `v` notation used for "point to light" and "point to eye" vectors in the lecture slides.
* A good exercise: place your favourite mug on your desk and look at the diffuse and specular shading. Move your head further away, but keep the same "`v` direction".
    * You'll notice it is mostly unchanged.
    * This suggests the answer is _yes_, they are unit since the distance doesn't affect the shading.
* The real dot product is bilinear i.e. `au dot bv = ab(u dot v)` for scalar `a, b`.
    * So when computing our diffuse and specular components in the Blinn-Phong shading model, using non-unit vectors will scale the outcome.
    * (the "infinitely far away" directional light shouldn't produce an infinitely bright spot on the object.)
