### ISSUE TITLE
Wrong corner for triangle.json

### ISSUE THREAD

**Issue by Mincelot** [dilevin/computer-graphics-ray-tracing#3]
I noticed that the file triangle.json has one of it's corner set to a huge number
[-0.5,0,0],
[0.5,0,0],
[0,8660254038,0] <- This one
I'm pretty sure it should have a decimal point and should be [0,0.8660254038,0], otherwise it will look like a rectangle in the final image.

**Comment by dilevin** [comment]
Yes, the decimal point is missing (it should be the same as triangle.json in A2).

**Comment by dilevin** [comment]
I've fixed this in the .json file. It should work properly now.
