### ISSUE TITLE
Lambertian shading too dark?

### ISSUE THREAD

**Issue by ginkxo** [dilevin/computer-graphics-ray-tracing#31]
This is what my sphere looks like just with diffuse shading, and it seems too dark particularly when I add in the specular component (the darkest part of the shadow on the sphere seems to take up the entire half of the sphere itself). I've tried to check if my vectors are properly normalized and calculated correctly[1], and so on, but can't seem to pinpoint why this might be too dark. Has anyone come across a similar issue or might know what the key issue is?

<img width="279" alt="ambientball" src="https://user-images.githubusercontent.com/21148289/73414367-9fd50e80-42dc-11ea-97dd-f36d2358692a.png">

[1] my n is calculated from my first_hit, and my l is (as described in the text book) the position of the light source minus the intersection point of the ray with the object

**Comment by gabriellemadden** [comment]
there are two light sources in this scene, it looks like you are only rendering one of them

**Comment by AnqiGao98** [comment]
same problem.....

**Comment by radiolariax** [comment]
thanks, that makes sense. If I'm understanding correctly the other light source is a DirectionalLight, which means that it isn't properly rendering for some reason?

**Comment by AnqiGao98** [comment]
> thanks, that makes sense. If I'm understanding correctly the other light source is a DirectionalLight, which means that it isn't properly rendering for some reason?

thanks, fixed

**Comment by radiolariax** [comment]
actually, it looks like I'm still having some issues, my DirectionalLight return vector is on the order of e^-310, meaning it is basically zero, so the light doesn't show up. Is there something I'm missing in the slides that deals with this issue?

**Comment by AnqiGao98** [comment]
> actually, it looks like I'm still having some issues, my DirectionalLight return vector is on the order of e^-310, meaning it is basically zero, so the light doesn't show up. Is there something I'm missing in the slides that deals with this issue?

I don't quite get ur issue, but I fixed mine in DirectionLight by change direction into opposite: d = -d

**Comment by radiolariax** [comment]
thanks, it turns out I wasn't properly initializing d because of it having the same name as the output variable, oops!

**Comment by darren-moore** [comment]
Nasty bug! Many C++ developers prefix member variables with `m_` to prevent things like this. I usually don't like Hungarian notation, but this distinction is essential.
