### ISSUE TITLE
Dark circle around sphere 

### ISSUE THREAD

**Issue by AnqiGao98** [dilevin/computer-graphics-ray-tracing#32]
Hi, 

I have the correct output when testing sphere-and-plane. 
But when I run the case two-spheres-and-plane and spheres-packing, I have a dark circle around each sphere as shown below... I was wondering anyone know what could be wrong? 

![image](https://user-images.githubusercontent.com/29612782/73417523-57225300-42e6-11ea-965b-b24f4f1985a7.png)
![image](https://user-images.githubusercontent.com/29612782/73417531-5e496100-42e6-11ea-8f1a-ff21302b3f00.png)

Thanks in advance!

**Comment by razasy299** [comment]
Self shadow.

**Comment by darren-moore** [comment]
Perhaps the reflected rays are incorrect? Make sure the vector reflection function is correct and that you're correctly setting the origin and direction of the reflected ray.

**Comment by AnqiGao98** [comment]
> Perhaps the reflected rays are incorrect? Make sure the vector reflection function is correct and that you're correctly setting the origin and direction of the reflected ray.

Yes, I made mistakes in reflected rays. Thanks!
