### ISSUE TITLE
inside-a-sphere shadow problems

### ISSUE THREAD

**Issue by ginkxo** [dilevin/computer-graphics-ray-tracing#36]
<img width="429" alt="verydark" src="https://user-images.githubusercontent.com/21148289/73480657-4a464380-4368-11ea-9cfe-50454afa1ebd.png">

this might be a bit hard to see, but the planes and sphere are showing up, however they are extremely dark as you can see. I'm trying to understand why this might be the case. So far, the other ones I've tested (everything except mirror.json and bunny.json) are working fine. Also, the interior sphere appears "solid" rather than seeing the interior of it.

I tried to turn off the shadow generating code and I got what I would expect to get without the shadows. This image is identical regardless of whether or not I turn off the recursive calls for the reflection:

<img width="276" alt="verydark3" src="https://user-images.githubusercontent.com/21148289/73482580-fccbd580-436b-11ea-8ae0-3435be764c24.png">

So I suspect the problem is in how I implement my shadows.

I attempted to follow the textbook algorithm as close as I could (p. 86):

<img width="278" alt="textalgo" src="https://user-images.githubusercontent.com/21148289/73482649-2127b200-436c-11ea-8de2-315903193134.png">

- Ambient light effects on pixel colours are added beforehand (as in the pseudocode) 
- Iterating through every light, I construct a shadow_ray using the origin as the q calculated from the blinn_phong_shading's input ray (e+td in the pseudocode) plus the t value found from the first_hit in the raycolor (in the above pseudocode this resulting q vector is the "p") , and the light direction unit vector "l" as the shadow_ray direction (altogether shadow_ray is defined in the pseudo code as "p + sl" )
- I check !first_hit, called on the shadow_ray, min_t = fudge_factor 1e-6, and the same entire list of objects passed in, and if this if-condition passes (so there is no hit) I calculate the diffuse and specular components as normal and add them to the output_color. Note that in calling first_hit here I don't find any use for the output hit_id here, or the new t and n values produced by the shadow ray (which makes sense if we only care about first_hit not hitting anyway). 
- output_color is returned as usual 

Let me know if anything seems off?

**Comment by NPTP** [comment]
This won't answer your question directly, but check out issue #4 . This image and one other will not be tested

**Comment by darren-moore** [comment]
Awesome start, narrowing it down to the shadows. Draw a picture of a plane casting a shadow on a point. Now move the light closer to the point. Is it still in shadow? Make sure you're taking into account the distance between the point and the light.

**Comment by radiolariax** [comment]
Thanks very much, totally forgot to take into account the point-light distance when comparing to the respective one with the shadow in the checks.
