### ISSUE TITLE
Image is very bright

### ISSUE THREAD

**Issue by RaihanFaruque** [dilevin/computer-graphics-ray-tracing#38]
This is the image I get :
![rgb](https://user-images.githubusercontent.com/59985990/73492878-92bd2b80-437f-11ea-9b05-be86fe865534.png)

Does anyone know why?

**Comment by darren-moore** [comment]
I can't see the image. Can you try editing/ adding a new comment?

**Comment by RaihanFaruque** [comment]
Here: 
![bright](https://user-images.githubusercontent.com/59985990/73493171-34447d00-4380-11ea-990d-38a6024e69e9.png)

**Comment by darren-moore** [comment]
My first thought would be to make sure you're taking into account the light intensity values. Is your `sphere-and-plane` also very bright like this?

**Comment by RaihanFaruque** [comment]
Yes, its also very bright

**Comment by darren-moore** [comment]
Make sure you're careful with the magnitude of vectors. See https://github.com/dilevin/computer-graphics-ray-tracing/issues/29
