### ISSUE TITLE
Light position is different 

### ISSUE THREAD

**Issue by RaihanFaruque** [dilevin/computer-graphics-ray-tracing#40]
This is the image I get
![Screenshot from 2020-01-30 19-15-01](https://user-images.githubusercontent.com/59985990/73502014-a1aed880-4395-11ea-9f1e-7f064381760e.png)
In my image, the specular highlights are at different place compared to the reference image. What is causing this issue?

**Comment by RaihanFaruque** [comment]
same thing happens here
![Screenshot from 2020-01-30 19-59-21](https://user-images.githubusercontent.com/59985990/73503803-4253c700-439b-11ea-999b-409477086c42.png)

**Comment by darren-moore** [comment]
I'd guess one of the directional light or point light directions you return are incorrect. https://github.com/dilevin/computer-graphics-ray-tracing/issues/25 or https://github.com/dilevin/computer-graphics-ray-tracing/issues/29 may help

**Comment by RaihanFaruque** [comment]
Ah forgot to normalize the ray direction
