### ISSUE TITLE
Everything looks good - except it's too bright.

### ISSUE THREAD

**Issue by NPTP** [dilevin/computer-graphics-ray-tracing#46]
Hi,
I've got everything looking fairly solid, except every image is just *too bright*. Here are some examples.

My sphere-packing:
![image](https://user-images.githubusercontent.com/16977354/73583674-8f01d580-4461-11ea-9bcd-9afd7a9c6fb6.png)

Solution sphere-packing:
![image](https://user-images.githubusercontent.com/16977354/73583678-932df300-4461-11ea-9a49-f6c347d87607.png)

My bunny:
![image](https://user-images.githubusercontent.com/16977354/73583708-c7a1af00-4461-11ea-801a-a585422a14dd.png)

Solution bunny:
![image](https://user-images.githubusercontent.com/16977354/73583713-cd979000-4461-11ea-943a-29133e810a2b.png)

As you can see (and it's like this for other images as well), everything looks correct except the overall brightness.

I am not adding the ambient light inside of a loop (only once per call to blinn_phong_shading()). I am scaling ambient by ka and the constant ia=01. I am scaling Lambertian by using kd * I * max(0, n.dot(l)). I am scaling specular by ks * I * (max(0, n.dot(h))^p (where p is the phong exponent). The recursive reflections appear to be working correctly and they are being scaled by the km coefficients of the object that was hit.

I'm totally stumped! Any ideas?

Thank you!

**Comment by darren-moore** [comment]
* Could you be reflecting more than once, for each light source? You shouldn't do this.
* Try normalizing directly in the formula, just as a sanity check e.g. `n.normalized().dot(l.normalized())`
* Are you initializing the rgb rays correctly to 0?

**Comment by NPTP** [comment]
Hey Darren, thanks for your feedback. I was rendering mirror.json again on one machine while debugging on another (took a while!) The output showed the mirror being much brighter than the solution image, while the walls/planes looked close to the solution. This lead me to go back to what I'm doing with my reflections, and indeed, I was not properly initializing the rays that get reflected out from a hit, so that the summed values returned from recursive calls would be artificially inflated/brighter. Now after a quick fix, things look great. (I had put that normalization sanity check all over the place though in the process haha)
