### ISSUE TITLE
Reflections not showing up 

### ISSUE THREAD

**Issue by lnvariant** [dilevin/computer-graphics-ray-tracing#47]
I'm having trouble with reflections showing up in sphere-packing on the spheres. I have followed the slides and the book, and can't seem to figure out why exactly it's not working. I am recursively sending reflection rays which themselves send rays, up until the limit (10). 

![Capture](https://user-images.githubusercontent.com/11165387/73585910-02144780-4474-11ea-80a8-f944cfa51b04.PNG)

The sphere plane looks fine:

![2](https://user-images.githubusercontent.com/11165387/73585929-4e5f8780-4474-11ea-858d-e958c8c0b8d7.PNG)

**Comment by darren-moore** [comment]
Turn down the number of reflections to just 1 when debugging reflections. Though, the speculars in your `sphere-packing` example look off. Are the speculars correct if you turn off reflections?

**Comment by lnvariant** [comment]
> Turn down the number of reflections to just 1 when debugging reflections. Though, the speculars in your `sphere-packing` example look off. Are the speculars correct if you turn off reflections?

The image looks exactly the same after changing to only 1 reflection. Does this mean there's a problem in my blinn_phong_shading?

EDIT:

turning off reflections:

![3](https://user-images.githubusercontent.com/11165387/73586106-dba3db80-4476-11ea-8b28-e936d5d5a5b5.PNG)

**Comment by darren-moore** [comment]
should look something like this without reflections. Note the specular highlight
![image](https://user-images.githubusercontent.com/16497418/73586177-6a185d00-4477-11ea-918f-b88c9aeb3483.png)

**Comment by lnvariant** [comment]
> should look something like this without reflections. Note the specular highlight

Which makes me wonder why it's breaking for three spheres but works fine to sphere and plane?

**Comment by lnvariant** [comment]
Running it in release build fixed the issue. Don't understand why.
