### ISSUE TITLE
How do we use max_t

### ISSUE THREAD

**Issue by pjsmith97** [dilevin/computer-graphics-ray-tracing#48]
Hey, still working on the assignment due to circumstances.

Exactly what is the purpose of max_t? It might have something to do with the problem I'm having, where part of the sphere isn't getting anything but ambient light.

Here is the diffuse image with just ambient light.

![rgb (1)](https://user-images.githubusercontent.com/48391420/73612888-f339ac00-45bd-11ea-91fa-c1887817ab59.png)

I do want to stress that I understand _what_ max_t is, but I don't understand what we do with it.

**Comment by darren-moore** [comment]
Are you taking into account both light sources?

`max_t`, along with the direction vector can be used to determine the distance from the point to a light source. You'll find it useful in shadow computations. I don't think that's your issue here.

**Comment by pjsmith97** [comment]
I do iterate over all the lights (And have point and directional covered). I noticed that in the first instance of finding _n_ dot _l_ (this is the directional light) it's a negative value. I can't tell if it's on the sphere in this instance, but is it possible I'm having sign issues?

**Comment by pjsmith97** [comment]
Figured it out. I misunderstood d from directional light. Didn't realize it was the direction from the light, not the scene.
