### ISSUE TITLE
MarkUs submission requirements

### ISSUE THREAD

**Issue by jennicao** [dilevin/computer-graphics-ray-tracing#64]
MarkUs requires us to submit the files from A2 in addition to the files for this assignment. But in the README it says that we can use precompiled binaries if we don't trust our A2 solutions.

So, I'm just double checking if the A2 files are still requires for A3 submission on MarkUs?

Second question: I also don’t see creative.json as a required submission. Does that mean we don’t need to submit it? 

![image](https://github.com/user-attachments/assets/57d9387d-70f4-4a41-88b0-90edf30899a8)

**Comment by vpnda** [comment]
Hey, you shouldn't need to submit those files but it'll help us understand what you are trying to do if we cannot make your provided solution compile. 

I've updated MarkUs with `creative.json`. Sorry about that!
