### ISSUE TITLE
reflect.cpp: Normalize or don't normalize?

### ISSUE THREAD

**Issue by jennicao** [dilevin/computer-graphics-ray-tracing#65]
The header file for reflect.cpp says "\_unit\_" for each input and output, but Tutorial 3 says not to normalize. Which should we follow?

![image](https://github.com/user-attachments/assets/5507bb1e-e07b-4994-99e4-63ef11e69f6a)

![image](https://github.com/user-attachments/assets/6e8ea14f-fde0-40eb-a106-108f6a584309)

**Comment by vpnda** [comment]
You should follow what the tutorial mentions.
