### ISSUE TITLE
min_t value

### ISSUE THREAD

**Issue by yangh122** [dilevin/computer-graphics-ray-tracing#66]
When we call the first hit function, what should the min_t value be, 1.0 or 0?

**Comment by vpnda** [comment]
You should be using the value passed in from `raycolor.cpp`. That function is called by `main.cpp` which [is 1](https://github.com/dilevin/computer-graphics-ray-tracing/blob/master/main.cpp#L44)

**Comment by milomg** [comment]
If we use the value 1.0 for all calls to raycolor, won't our reflections be broken & not match the rendered examples?
