### ISSUE TITLE
blinn phong shading math?

### ISSUE THREAD

**Issue by dharhar** [dilevin/computer-graphics-ray-tracing#67]
I've implemented the math from the tutorial slides but am getting this output. Any ideas on what could be going wrong?
![image](https://github.com/user-attachments/assets/f8169305-8d50-43cd-809a-ec8e19a09f74)

**Comment by vpnda** [comment]
Try using the sphere image. Are you also adding ambient light?

**Comment by dharhar** [comment]
I added ambient light outside of the loop going over all lights. When I used sphere.json, I just get a black screen, but my color values are all 0.0x
