### ISSUE TITLE
Strange inside-a-sphere result

### ISSUE THREAD

**Issue by milomg** [dilevin/computer-graphics-ray-tracing#71]
<img width="762" alt="Screenshot 2024-09-27 at 11 57 45 AM" src="https://github.com/user-attachments/assets/16c772f1-7626-40f5-abac-89df1f4ff520">

Some important constants I use:
`raycolor(ray,1e-4,objects,lights,0,rgb);` - from main.cpp (the same constant is passed into recursive calls)

I add `+ 1e-9 * n` to the shadow_ray and the mirror_ray

I do `first_hit(shadow_ray, 1e-4, ...)`

I stop raycolor when `num_recursive_calls > 5`

Possibly related to #69

**Comment by FalakR** [comment]
Same, I am also getting something similar but incorrect obviously

<img width="632" alt="Screenshot 2024-09-28 at 12 30 19 AM" src="https://github.com/user-attachments/assets/70656fc8-94cb-4573-8219-815c087f3467">

**Comment by pranavrao145** [comment]
I'm also having a similar issue, if I keep the default `min_t` to `first_hit` (which I believe is 1.0), I'm able to get the same as @FalakR above, but if I use `min_t = 1e-4` or some small number, I get the picture from the original issue.

**Comment by racheldengg** [comment]
I had a similar issue and it turns out that my shadow ray was not normalized in bling_phong_shading.cpp before I passed it into first_hit

**Comment by milomg** [comment]
Thanks, that worked! (and that also explains why it wasn't working, the `t` values that I was comparing wasn't comparing distances correctly because velocity was different)
