### ISSUE TITLE
Values for k_d, k_s and p

### ISSUE THREAD

**Issue by gursi26** [dilevin/computer-graphics-ray-tracing#73]
How do we get the values for  k_d, k_s and p for the blinn phong shading model? I cannot find them anywhere in the file.

**Comment by FalakR** [comment]
In Object.h you can find the material attribute which corresponds to the Material struct (can be found in Material.h) and there you'll find all 4 i.e., ks, kd, ks, and km

**Comment by vpnda** [comment]
+1 to FalakR's comment
