### ISSUE TITLE
Light Spots Inconsistency

### ISSUE THREAD

**Issue by Vesnushkin** [dilevin/computer-graphics-ray-tracing#74]
Hey!

It seems like everything is quite okay, however the **two light dots** (one each ball) seem to be closer together than they need to be:
<img width="643" alt="Screenshot 2024-09-27 at 9 09 52 PM" src="https://github.com/user-attachments/assets/80454db0-5d0a-4122-b6fb-debf25ec9673">
^ Mine ^
![sphere-packing](https://github.com/user-attachments/assets/29135145-c56b-4269-8d39-7873eff8563e)
^ Provided picture ^

I'm not sure what the issue is, I've been trying to edit my implementations but it doesn't seem to resolve it. Any insights?

**Comment by vpnda** [comment]
You can try using [imagemagick](https://imagemagick.org/script/compare.php) CLI to find more debugging info. If your picture is off by just a few pixels we won't penalize you for it.

**Comment by lulu-yunze** [comment]
Hey, did you ever figure out the problem? I am having the exact same issue with the two light dots being closer than expected.

**Comment by Vesnushkin** [comment]
I was able to fix this issue by properly calculating the $H$ vector! (I needed to put a negative sign on on a vector, and properly normalize all the components).
