### ISSUE TITLE
Discrepancy in Tutorial and Assignment instructions

### ISSUE THREAD

**Issue by FalakR** [dilevin/computer-graphics-ray-tracing#75]
In Tutorial 3 slides, for reflect.cpp, it says not to normalize cause we want the out vector to be of the same length as in. 
However in the header file of reflect, it says that inputs are unit vectors in and n and out vector which should be a unit vector which should be returned. So what instruction should be followed. 

<img width="1226" alt="Screenshot 2024-09-27 at 9 29 03 PM" src="https://github.com/user-attachments/assets/23351501-7366-402d-877d-de12565f650a">
<img width="644" alt="Screenshot 2024-09-27 at 9 29 28 PM" src="https://github.com/user-attachments/assets/96861b7b-d303-4ffc-a438-e6f386612f59">

**Comment by jennicao** [comment]
#65 says to follow tutorial and don’t normalize

**Comment by FalakR** [comment]
Solved
