### ISSUE TITLE
Very small difference in sphere-packing

### ISSUE THREAD

**Issue by pranavrao145** [dilevin/computer-graphics-ray-tracing#79]
Hello,

When comparing the output `sphere-packing.json` with ImageMagick, I'm having a very very small difference between the expected output and mine. Below is the difference (red specks):

![difference](https://github.com/user-attachments/assets/1fff3296-08ef-488f-97b3-051b38dff06d)

I suspect the fudge factor but nothing I've tried has worked so far. To get the output above, I'm adding `1e-9 * n` to the origins of both the mirror ray and the shadow ray, and passing in `1e-4` as `min_t` to `first_hit` in both of these scenarios. Every change I've tried so far has made it stay either the same or made it much worse.

Does anyone have any ideas on how I can fix this? Thanks in advance!

**Comment by jennicao** [comment]
I had something similar and I increased my maximum recursion depth by 1 to fix this

**Comment by FalakR** [comment]
So should we keep the max_depth as 10 or 11 in that case ?

**Comment by jennicao** [comment]
Whichever works for you, I think. I have it at 11

**Comment by pranavrao145** [comment]
I can confirm that setting it at 11 does in fact fix my problem. Thanks a lot @jennicao!

**Comment by jennicao** [comment]
Awesome! Glad I could help :)
