### ISSUE TITLE
Brighter reflection in sphere and plane

### ISSUE THREAD

**Issue by FaithfulZhening** [dilevin/computer-graphics-ray-tracing#8]
My result of reflection in Sphere-and-Plane is slightly brighter than given image. However, the reflections of all other images are the same as given one. Can you confirm that the km coefficient given in sphere-and-plane.json is correct?

**Comment by disconcision** [comment]
In the absence of an answer, I'm wondering whether anyone is actually getting a reflection which appears exactly as in the example image

**Comment by dilevin** [comment]
small differences in the images will not affect your grade. TAs will look at the actual implementation to verify the algorithm is correct.
