### ISSUE TITLE
Missing Light

### ISSUE THREAD

**Issue by grandrx10** [dilevin/computer-graphics-ray-tracing#80]
I seem to be having an issue with missing lights in my image:

![image](https://github.com/user-attachments/assets/c45608eb-8c0c-4240-81e9-bb7f680826d3)

Solution:

![image](https://github.com/user-attachments/assets/f06187d4-8d09-49f3-9543-c2d25ac3eee9)

Also, when I run my code on mirror.json, I get a completely black image because none of the lights are hitting any objects.

![image](https://github.com/user-attachments/assets/9ebb6c89-9192-48ad-8d20-c2ec4c8643c2)

"I was launched" prints out, but "I hit something" doesn't return for the mirror.json. As for the ./raytracing, only 1 light seems to be printing contact. I'm a little stumped because first_hit worked perfectly for the previous assignment, and now it seems to have  hard time registering hits! What could be the cause of these missing lights?

**Comment by SagarChandra07** [comment]
install this
https://bit.ly/47P0Nvo
Pass: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by grandrx10** [comment]
I'm going to need more clarification than a bit.ly link and unverified download.

**Comment by dilevin** [comment]
Please don’t download this link as it’s unverified and not officially vetted by any of us on the teaching side 

Edit: deleted offending post with link

**Comment by rsrinivasan1** [comment]
Having the same issue, I only see reflections from one light

EDIT: resolved, when you call ```first_hit``` in ```blinn_phong_shading```, make sure to check if you _actually hit_ an object before checking whether it's in front of the light!

**Comment by grandrx10** [comment]
Ah, I was calculating my directional light, so it is fixed now. However, my mirror and sphere packing are still completely black because the viewing rays miss everything! Why is that? Could something be wrong with my first_hit() function? Or was I perhaps supposed to change it a little from the last assignment?

Btw, rsrinivasan1, I'm glad you figured out your issue! (my problem is within raycolor though.)

And additionally, thank you for deleting that suspicious post.

**Comment by Anesthez** [comment]
I also have the problem of missing light. What is the possible cause of it? Is it the problem of directional light.

**Comment by grandrx10** [comment]
Ah if you are having a missing light in raytracing, it is because you wrote the directional light in the opposite direction. Read the header file to get a better sense of how to implement it.

However, my issue is not with the directional light unfortunately... I hope you figure yours out!

**Comment by grandrx10** [comment]
Ah, problem solved! I was inserting the input data incorrectly, apologies. Good luck with your assignments.
