### ISSUE TITLE
slight difference in bunny output and actual render

### ISSUE THREAD

**Issue by gursi26** [dilevin/computer-graphics-ray-tracing#85]
There is a slight difference in the bunny rendered by my code and the sample renders

my bunny:
![bunny](https://github.com/user-attachments/assets/d2139a41-cb51-4028-9ad2-9cc791e91558)

expected output:
![expected-bunny](https://github.com/user-attachments/assets/4a57a85e-0690-458d-bf1f-750a67d33ab1)

The difference can be seen in the shadow right below the bunny's head, among other small differences in other locations.

Is this a problem or just to do with the choice of a constant (recursion depth, fudge factor)?

**Comment by vpnda** [comment]
It might be one of those two. We don't expect a perfect representation of the image. If there are some pixels that are off here and there, its ok.
