### ISSUE TITLE
Very bright ambient component

### ISSUE THREAD

**Issue by TeamSegFault** [dilevin/computer-graphics-ray-tracing#9]
My image with just the ambient component is very bright. It appears that Ka and Kd of the sphere are the same and Ka and Kd of the plain is also the same. Ka and Kd are [1, 0.7, 0.2] for the sphere and [0.2, 0.3, 0.8] for the plain. Should Ka be this large?

**Comment by alexei-zolotarevschi** [comment]
If you haven't tried this yet, when setting the ambient part of the "full blinn-phong model" you need to also multiply those Ka values by the intensity of the ambient light in the scene. If you have the textbook, it's explained better in section 4.5.3 , in the equation 4.3.  
For the assignment, there is a comment in the blinn-phong_shading.h which says "Use a hard-coded value of ia=0.1 for ambient light."

**Comment by TeamSegFault** [comment]
I see, thanks!
